SCR_EditorActionList {
 m_Actions {
  TW_LootSettings_ToolbarAction "{65E6A11CAC711C34}" {
   m_Info SCR_UIInfo "{65E6A11C95B7AC43}" {
    Name "Lootmap"
    Icon "{42484F03A5B5B395}UI/Textures/Editor/Toolbar/ToolbarFilter_Systems.edds"
   }
   m_ActionGroup TOOLS
   m_iOrder 32
  }
 }
}